/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bank;

/**
 *
 * @author Yuzron
 */
public class Simpan extends javax.swing.JFrame {

    /**
     * Creates new form Simpan
     */
    public Simpan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTSimpanUang = new javax.swing.JTextField();
        jBBenar = new javax.swing.JButton();
        jBKembali = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Masukkan berapa jumlah yang ingin anda simpan :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 60, 420, 30);

        jTSimpanUang.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(jTSimpanUang);
        jTSimpanUang.setBounds(110, 110, 210, 60);

        jBBenar.setText("BENAR");
        jBBenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBenarActionPerformed(evt);
            }
        });
        getContentPane().add(jBBenar);
        jBBenar.setBounds(240, 240, 100, 40);

        jBKembali.setText("KEMBALI");
        jBKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBKembaliActionPerformed(evt);
            }
        });
        getContentPane().add(jBKembali);
        jBKembali.setBounds(20, 240, 100, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon("E:\\PB OBJEK\\pict GUI\\download.jpg")); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(340, 280, 210, 120);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 630, 430);

        setSize(new java.awt.Dimension(547, 453));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBBenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBenarActionPerformed
        int saldo = 5000000;
        int nambahsaldo = Integer.parseInt(jTSimpanUang.getText());

        int hasilnambah = saldo + nambahsaldo;

        String j = String.valueOf(hasilnambah);
        HasilPenarikan a = new HasilPenarikan(j);
        a.show();
        dispose();

    }//GEN-LAST:event_jBBenarActionPerformed

    private void jBKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBKembaliActionPerformed
        MenuATM a = new MenuATM();
        a.show();
        dispose();
    }//GEN-LAST:event_jBKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Simpan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Simpan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Simpan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Simpan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Simpan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBenar;
    private javax.swing.JButton jBKembali;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTSimpanUang;
    // End of variables declaration//GEN-END:variables
}
